### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by Steelx377Yao** [AndroidModLoader/GTASA_GPS#3]
When the destination is far away, the route is incomplete, wrong or not displayed.
![0](https://user-images.githubusercontent.com/109135215/178434497-a88787da-51db-49cc-85e1-fba7d4dc8cfc.jpg)
![1](https://user-images.githubusercontent.com/109135215/178434507-d2d1370c-5b94-4e09-a02c-784035dc6303.jpg)

**Comment by AndroidModLoader** [comment]
The game doesnt provide enough data and also sometimes giving wrong

**Comment by RusJJ** [comment]
That was a game limit that is fixed in gta5 hud mod. Will be fixed soon

**Comment by CjStraightBusta** [comment]
![Screenshot_20221126-224939](https://user-images.githubusercontent.com/119123374/204097351-cf560351-ba0b-402b-acd0-2b223124d8ab.jpg)
Why i can't delete the marker

**Comment by RusJJ** [comment]
Because do not place it right in front of a player or do not change values in ini like a crazy

**Comment by CjStraightBusta** [comment]
I've tried remotely but still can't delete it

**Comment by CjStraightBusta** [comment]
How to remove?


Pada tanggal Min, 27 Nov 2022 18:48, [-=KILL MAN=-] <
***@***.***> menulis:

**Comment by AndroidModLoader** [comment]
Will be fixed in upcoming update
