### ISSUE TITLE
GPS not work in San Fierro

### ISSUE THREAD

**Issue by Mirko2893** [AndroidModLoader/GTASA_GPS#5]
When i put a marker in San Fierro and i start to drive it doesn't work and not show any GPS.

https://github.com/user-attachments/assets/dd0b99d2-ec16-469e-b414-91af0924f2f2

**Comment by RusJJ** [comment]
Maybe you should use the latest GPS version, how do you think?

**Comment by Mirko2893** [comment]
I usted the latest version, in a old versión it works well, but when i use
the latest version it don't work in San Fierro

**Comment by RusJJ** [comment]
Ok, what is the latest version?

**Comment by Facebookcom-gig** [comment]
Please update the mod; it only works on Los Santos but constantly disappears on the other islands.
